### ISSUE TITLE
Discord Link out of date

### ISSUE THREAD

**Issue by Bone2510** [loki79uk/FS25_PlayerMovement#4]
Hey Loki,
Since I couldn't find any other way to contact you, I wanted to let you know that you can no longer be reached via the Discord link in your profile.
Originally I wanted to ask you for approvals for a small part of your script, but unfortunately I couldn't reach you via Discord.

**Comment by loki79uk** [comment]
I don't think it has ever worked, but if you try searching for the name, plenty of other people have managed it.

**Comment by loki79uk** [comment]
Have you tried messaging me?  I have not seen anything with your username.

**Comment by Bone2510** [comment]
No, unfortunately I didn't find you anywhere else than here.
